name: Build only

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dart-lang/setup-dart@v1

      - uses: nttld/setup-ndk@v1
        id: ndk
        with:
          ndk-version: 'r29'
          add-to-path: false

      - name: Install build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make meson nasm autoconf automake libtool
          pip3 install --user Jinja2
          pip3 install --user jsonschema
          echo "$HOME/.local/bin" >> "$GITHUB_PATH"

      - name: Dart pub get
        run: dart pub get -C build-scripts

      - name: Build for arm32
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
        run: dart run build-scripts/android/android.dart --action=build --abis=arm32

      - name: Build for arm64
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
        run: dart run build-scripts/android/android.dart --action=build --abis=arm64

      - name: Build for x86
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
        run: dart run build-scripts/android/android.dart --action=build --abis=x86

      - name: Build for x86_64
        env:
          ANDROID_NDK_HOME: ${{ steps.ndk.outputs.ndk-path }}
        run: dart run build-scripts/android/android.dart --action=build --abis=x86_64

      - name: Archive artifacts
        run: dart run build-scripts/android/android.dart --action=bundle --abis=arm32,arm64,x86,x86_64

      - uses: actions/upload-artifact@v7.0.1
        with:
          path: out/artifacts/android-binaries.zip
          if-no-files-found: error
          archive: false

  apple:
    name: Build Apple (${{ matrix.link-type }})
    runs-on: macos-latest
    strategy:
      fail-fast: true
      max-parallel: 1
      matrix:
        link-type: [static, shared]
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1

      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0'

      - name: Cache iOS simulator runtime
        id: ios-runtime-cache
        uses: actions/cache@v4
        with:
          path: |
            /Library/Developer/CoreSimulator/Volumes
            /Library/Developer/CoreSimulator/Cryptex
          key: ios-runtime-xcode-26.0

      - name: Install iOS platform
        run: sudo xcodebuild -downloadPlatform iOS

      - name: Install build tools
        run: brew install meson ninja pkg-config nasm yasm automake autoconf libtool

      - name: Add Rust targets & install cargo-c
        run: |
          rustup target add aarch64-apple-darwin x86_64-apple-darwin aarch64-apple-ios aarch64-apple-ios-sim
          cargo install cargo-c

      - name: dart pub get
        run: dart pub get -C build-scripts

      - name: Build macos-arm64
        run: |
          dart run build-scripts/apple/apple.dart \
            --action=build \
            --targets=macos-arm64 \
            --link-type=${{ matrix.link-type }}

      - name: Build macos-x86_64
        run: |
          dart run build-scripts/apple/apple.dart \
            --action=build \
            --targets=macos-x86_64 \
            --link-type=${{ matrix.link-type }}

      - name: Build ios-arm64
        run: |
          dart run build-scripts/apple/apple.dart \
            --action=build \
            --targets=ios-arm64 \
            --link-type=${{ matrix.link-type }}

      - name: Build iossim-arm64
        run: |
          dart run build-scripts/apple/apple.dart \
            --action=build \
            --targets=iossim-arm64 \
            --link-type=${{ matrix.link-type }}

      - name: Bundle xcframeworks
        run: |
          dart run build-scripts/apple/apple.dart \
            --action=bundle \
            --targets=macos-arm64,macos-x86_64,ios-arm64,iossim-arm64 \
            --link-type=${{ matrix.link-type }}

      - uses: actions/upload-artifact@v7.0.1
        with:
          name: apple-binaries-${{ matrix.link-type }}.zip
          path: out/artifacts/apple-binaries-${{ matrix.link-type }}.zip
          if-no-files-found: error
          archive: false
